# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779c5ac5f177d8a7fecb72936571e40e5bbc077a97fe0d6739d6967211fcb87c7b27708707dc070f2fff27c90b5b779d5334f50343c8c27868997af19bf95395

test:
  secret_key_base: 8e7848789899e7d98be6e01697cbba6d43b25c5426eaefb436f890bc53cf704fc30d15d28efd1cf7681fbddce9d0b854b4d33b23b90b4f9bcbb0c4c783071e9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
